import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { setTimeout as delay } from 'node:timers/promises';
import path from 'node:path';
import { devFixture, counterSource } from './dev-fixture.mjs';
import { startServer, repositoryRoot } from './support.mjs';

test('generators rewriting identical files settle without a rebuild loop and source edits still rebuild', { timeout: 25_000 }, async t => {
  const fixture = await devFixture({config: `import {writeFileSync} from 'node:fs';
export default {basePath:'/docs',webpack(config){config.plugins.push({apply(compiler){
compiler.hooks.beforeCompile.tap('GenerateEveryBuild',()=>writeFileSync('generated.json','{"value":"unchanged"}'));
}});return config;}}`, files:{
    'components/Counter.jsx':counterSource().replace("import{useState}","import generated from '../generated.json';import{useState}").replace('Original {count}','{generated.value} {count}'),
  }});
  t.after(fixture.close);
  async function settled(previousBuild) {
    let last, stableSince = Date.now();
    for (let attempt=0; attempt<160; attempt++) {
      const state = await fixture.read('.prnext-dev.json').then(JSON.parse).catch(()=>({}));
      const current = state.state === 'ready' && state.buildId !== previousBuild ? state.buildId : undefined;
      if (!current || current !== last) stableSince = Date.now();
      if (current && Date.now()-stableSince >= 1500) return current;
      last = current;
      await delay(50);
    }
    assert.fail('generator rebuilds did not settle: '+fixture.output().slice(-4000));
  }
  const initial = await settled();
  assert.equal((fixture.output().match(/PRNext built /g)||[]).length,1,'generated bytes already compiled must not cause a second startup build');
  await fixture.write('components/Counter.jsx',counterSource('Changed'));
  const updated = await settled(initial);
  assert.notEqual(updated,initial);
  assert.match(await (await fetch(fixture.url+'/docs/pages')).text(),/Changed/);
});

test('native development SSE reports failed builds, is uncompressed and rejects cross-site and non-GET requests', { timeout: 25_000 }, async t => {
  const fixture = await devFixture();
  t.after(fixture.close);
  const url = fixture.url + '/docs/_prnext/dev';
  assert.equal((await fetch(url, { method: 'POST' })).status, 405);
  assert.equal((await fetch(url, { headers: { 'sec-fetch-site': 'cross-site' } })).status, 403);
  const abort = new AbortController();
  const timer = setTimeout(() => abort.abort(), 15_000);
  t.after(() => { clearTimeout(timer); abort.abort(); });
  const response = await fetch(url, { signal: abort.signal, headers: { 'accept-encoding': 'gzip' } });
  assert.equal(response.status, 200);
  assert.match(response.headers.get('content-type'), /text\/event-stream/);
  assert.equal(response.headers.get('cache-control'), 'no-store');
  assert.equal(response.headers.get('content-encoding'), null);
  const reader = response.body.getReader();
  let pending = '';
  async function event(predicate) {
    for (;;) {
      const end = pending.indexOf('\n\n');
      if (end >= 0) {
        const frame = pending.slice(0, end); pending = pending.slice(end + 2);
        const json = frame.split('\n').find(line => line.startsWith('data: '));
        if (json) { const value = JSON.parse(json.slice(6)); if (predicate(value)) return value; }
      } else {
        const next = await reader.read();
        assert.equal(next.done, false, 'SSE must stay open while the current valid server runs');
        pending += new TextDecoder().decode(next.value);
      }
    }
  }
  assert.ok((await event(value => value.state === 'ready')).buildId);
  await fixture.write('components/Counter.jsx', 'export default function Counter(){ return <bad');
  const failure = await event(value => value.state === 'error');
  assert.match(failure.error, /Counter.jsx/);
  assert.equal((await fetch(fixture.url + '/docs/pages')).status, 200, 'a failed build leaves the last valid server available');
  await reader.cancel();
});

test('production has no development endpoint even if a state file remains in the project', async t => {
  const root = await mkdtemp(path.join(repositoryRoot, '.prnext-dev-production-test-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(path.join(root, 'pages'));
  await writeFile(path.join(root, 'package.json'), '{"type":"module"}');
  await writeFile(path.join(root, 'pages/index.jsx'), 'export default function Page(){return <h1>Production</h1>}');
  await writeFile(path.join(root, '.prnext-dev.json'), '{"state":"error","error":"private development error"}');
  await promisify(execFile)(process.execPath, [path.join(repositoryRoot, 'packages/prnext/cli.mjs'), 'build', root]);
  const server = await startServer(root);
  t.after(server.close);
  const response = await fetch(server.url + '/_prnext/dev');
  assert.equal(response.status, 404);
  assert.doesNotMatch(await response.text(), /private development error/);
});
