import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, rm, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { build } from '../packages/prnext/build/index.mjs';
import { appFixture, startServer } from './support.mjs';

test('metadata files use native static routes, serialize data, and preserve request-dependent behavior', async () => {
  const fixture = await appFixture();
  let server;
  const put = async (name, content) => { const file = path.join(fixture.root, name); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, content); };
  try {
    await rm(path.join(fixture.root, 'app'), { recursive: true });
    await rm(path.join(fixture.root, 'proxy.ts'), { force: true });
    await rm(path.join(fixture.root, 'public/robots.txt'), { force: true });
    await put('prnext.config.mjs', `export default{basePath:'/docs'}`);
    await put('app/layout.jsx', `export default({children})=><html><body>{children}</body></html>`);
    await put('app/page.jsx', `export const metadata={title:'Files'};export default()=> <h1>Files</h1>`);
    await put('app/robots.ts', `export default()=>({rules:[{userAgent:['Bot','Other'],allow:'/',disallow:['/admin','/private'],crawlDelay:3,other:{'Custom-Rule':['one','two']}}],host:'https://example.com',sitemap:'https://example.com/sitemap.xml'})`);
    await put('app/sitemap.ts', `export default()=>[{url:'https://example.com/?a=1&b=2',lastModified:new Date('2026-01-02'),priority:0,alternates:{languages:{fr:'https://example.com/fr?a=1&b=2'}},images:['https://example.com/image.png'],videos:[{title:'A & B',thumbnail_loc:'https://example.com/thumb.jpg',description:'<safe>',duration:0}]}]`);
    await put('app/manifest.ts', `export default()=>({name:'PRNext test',start_url:'/docs',display:'standalone',icons:[]})`);
    await put('app/blog/sitemap.xml', '<?xml version="1.0"?><urlset><url><loc>https://example.com/blog</loc></url></urlset>');
    await put('app/live/sitemap.ts', `import {headers} from 'next/headers';export default async()=>[{url:'https://example.com/'+((await headers()).get('x-tenant')||'public')}]`);
    await put('app/[tenant]/sitemap.ts', `export function generateStaticParams(){return[{tenant:'alice'}]}export default async({params})=>[{url:'https://example.com/'+(await params).tenant}]`);
    const manifest = await build(fixture.root);
    assert.ok(manifest.prerendered.some(item => item.path === '/robots.txt'));
    assert.ok(manifest.prerendered.some(item => item.path === '/alice/sitemap.xml'));
    assert.ok(!manifest.prerendered.some(item => item.path === '/live/sitemap.xml'));
    const html = await readFile(path.join(manifest.outputDirectory, manifest.prerendered.find(item => item.path === '/').file), 'utf8');
    assert.match(html, /rel="manifest" href="\/docs\/manifest.webmanifest"/);
    server = await startServer(fixture.root);
    const get = (url, init) => fetch(server.url + '/docs' + url, init);
    const robots = await get('/robots.txt');
    assert.equal(robots.status, 200);
    assert.match(robots.headers.get('content-type'), /text\/plain/);
    assert.equal(await robots.text(), 'User-Agent: Bot\nUser-Agent: Other\nAllow: /\nDisallow: /admin\nDisallow: /private\nCrawl-delay: 3\nCustom-Rule: one\nCustom-Rule: two\n\nHost: https://example.com\nSitemap: https://example.com/sitemap.xml\n');
    assert.equal(await (await get('/robots.txt', { method: 'HEAD' })).text(), '');
    const sitemap = await get('/sitemap.xml');
    assert.match(sitemap.headers.get('content-type'), /application\/xml/);
    const xml = await sitemap.text();
    assert.match(xml, /a=1&amp;b=2/);
    assert.match(xml, /<lastmod>2026-01-02T00:00:00.000Z<\/lastmod>/);
    assert.match(xml, /<priority>0<\/priority>/);
    assert.match(xml, /<video:description>&lt;safe&gt;<\/video:description>/);
    assert.match(await (await get('/blog/sitemap.xml')).text(), /example.com\/blog/);
    assert.match(await (await get('/alice/sitemap.xml')).text(), /example.com\/alice/);
    const pwa = await get('/manifest.webmanifest');
    assert.match(pwa.headers.get('content-type'), /application\/manifest\+json/);
    assert.equal((await pwa.json()).name, 'PRNext test');
    const { stdout: processes } = await promisify(execFile)('ps', ['-eo', 'pid=,ppid=']);
    assert.ok(!processes.trim().split('\n').some(row => Number(row.trim().split(/\s+/)[1]) === server.child.pid), 'static metadata requests do not start a Node worker');
    assert.match(await (await get('/live/sitemap.xml', { headers: { 'x-tenant': 'one' } })).text(), /example.com\/one/);
    assert.match(await (await get('/live/sitemap.xml', { headers: { 'x-tenant': 'two' } })).text(), /example.com\/two/);
    await put('app/robots.txt', 'User-agent: *');
    await assert.rejects(build(fixture.root), /Conflicting metadata route/);
    assert.equal((await get('/robots.txt')).status, 200, 'failed builds preserve the running deployment');
  } finally { await server?.close(); await fixture.remove(); }
});
