import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';

const directory=path.resolve(process.argv[2]||'reports/blog-comparison');
const data=JSON.parse(await readFile(path.join(directory,'results.json'),'utf8'));
const engines=['next','rustyx'],names={next:'Next.js',rustyx:'Rustyx'};
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const median=values=>{const sorted=values.filter(Number.isFinite).sort((a,b)=>a-b);return sorted[Math.floor(sorted.length/2)]??null};
const fmt=(value,digits=2)=>Number.isFinite(value)?value.toLocaleString('fr-FR',{minimumFractionDigits:digits,maximumFractionDigits:digits}):'—';
function aggregate(rows,keys){return Object.fromEntries(keys.map(key=>[key,{median:median(rows.map(row=>row[key])),min:Math.min(...rows.map(row=>row[key]).filter(Number.isFinite)),max:Math.max(...rows.map(row=>row[key]).filter(Number.isFinite))}]))}
const build=Object.fromEntries(['cold','warm'].map(kind=>[kind,Object.fromEntries(engines.map(engine=>[engine,aggregate(data.builds.filter(row=>row.engine===engine&&row.kind===kind),['frameworkMs','validationMs','pipelineMs','cpuMs','sampledPeakTreeRssMiB'])]))]));
const runtime=data.method.scenarios.map(scenario=>({id:scenario.id,label:scenario.label,concurrency:scenario.concurrency,ratePerSecond:scenario.ratePerSecond,...Object.fromEntries(engines.map(engine=>{
  const rows=data.runs.filter(row=>row.engine===engine&&row.scenario===scenario.id),valid=rows.filter(row=>!row.error&&!row.errors&&row.cpuValid&&!row.reachedCap&&(!row.targetRatePerSecond||(Math.abs(row.requestsPerSecond/row.targetRatePerSecond-1)<=.05&&row.scheduleLagP95Ms<=10)));
  return[engine,{runs:rows.length,validRuns:valid.length,requests:rows.reduce((sum,row)=>sum+(row.requests||0),0),errors:rows.reduce((sum,row)=>sum+(row.errors||0),0),
    ...aggregate(valid,['requestsPerSecond','loadMedianRssMiB','sampledPeakRssMiB','cpuMsPerRequest','cpuPercentOneCore','p50Ms','p95Ms','p99Ms','ttfbP95Ms','meanBodyBytes','meanDecodedBytes','startupMs','scheduleLagP95Ms']),
    clientCpuPercent:median(valid.map(row=>100*row.clientCpuMs/row.elapsedMs)),idleRssMiB:median(valid.map(row=>row.idle.rssMiB))}];
}))}));
const browser=Object.fromEntries(['/','/blog/guide-to-using-images-in-nextjs/'].map(route=>[route,Object.fromEntries(engines.map(engine=>[engine,aggregate(data.browser.filter(row=>row.engine===engine&&row.route===route),['ttfbMs','domContentLoadedMs','loadMs','lcpMs','jsEncodedBytes','jsDecodedBytes','transferredBytes','mainThreadMs','scriptMs','jsHeapUsedMiB','resourceCount','scriptCount'])]))]));
const summary={date:data.finishedAt,status:data.status,versions:data.versions,machine:data.machine,build,runtime,browser,contentComparisons:data.contentComparisons};
await writeFile(path.join(directory,'summary.json'),JSON.stringify(summary,null,2)+'\n');
const mixed=runtime.find(row=>row.id==='mixed-4');
const fixed=runtime.find(row=>row.id==='fixed-250');
const gain=(n,r)=>100*(n-r)/n;
const percent=value=>(value>=0?'+':'')+fmt(value,1)+' %';
const winner=(n,r,lower=true)=>!Number.isFinite(n)||!Number.isFinite(r)?'—':Math.abs(n-r)/Math.max(n,r)<.03?'Proches':(lower?r<n:r>n)?'Rustyx':'Next.js';
const size=engine=>data.builds.filter(row=>row.engine===engine).at(-1)?.output;
const comparisons=[
  ['Build complet à froid, contrôles + RSS',build.cold.next.pipelineMs.median/1000,build.cold.rustyx.pipelineMs.median/1000,'s',true],
  ['Rebuild complet, caches conservés',build.warm.next.pipelineMs.median/1000,build.warm.rustyx.pipelineMs.median/1000,'s',true],
  ['CPU du build complet à froid',build.cold.next.cpuMs.median/1000,build.cold.rustyx.cpuMs.median/1000,'s CPU',true],
  ['Pic RAM du build complet à froid',build.cold.next.sampledPeakTreeRssMiB.median,build.cold.rustyx.sampledPeakTreeRssMiB.median,'Mio',true],
  ['RAM serveur, sept pages à 250 req/s',fixed.next.loadMedianRssMiB.median,fixed.rustyx.loadMedianRssMiB.median,'Mio',true],
  ['CPU par réponse, sept pages à 250 req/s',fixed.next.cpuMsPerRequest.median,fixed.rustyx.cpuMsPerRequest.median,'ms',true],
  ['Débit observé, sept pages / C4',mixed.next.requestsPerSecond.median,mixed.rustyx.requestsPerSecond.median,'req/s',false],
  ['Latence p95, sept pages à 250 req/s',fixed.next.p95Ms.median,fixed.rustyx.p95Ms.median,'ms',true],
  ['HTML gzip moyen, sept pages à 250 req/s',fixed.next.meanBodyBytes.median/1024,fixed.rustyx.meanBodyBytes.median/1024,'Kio',true],
  ['JavaScript reçu à l’accueil',browser['/'].next.jsEncodedBytes.median/1024,browser['/'].rustyx.jsEncodedBytes.median/1024,'Kio',true],
  ['Travail du thread principal à l’accueil',browser['/'].next.mainThreadMs.median,browser['/'].rustyx.mainThreadMs.median,'ms',true],
  ['DOMContentLoaded à l’accueil',browser['/'].next.domContentLoadedMs.median,browser['/'].rustyx.domContentLoadedMs.median,'ms',true],
  ['LCP de l’article, réseau local',browser['/blog/guide-to-using-images-in-nextjs/'].next.lcpMs.median,browser['/blog/guide-to-using-images-in-nextjs/'].rustyx.lcpMs.median,'ms',true],
  ['Fichiers de build hors cache',size('next').withoutCacheBytes/1024**2,size('rustyx').withoutCacheBytes/1024**2,'Mio',true],
];
const markdownTable=(headers,rows)=>`| ${headers.join(' | ')} |\n| ${headers.map(()=>'---').join(' | ')} |\n${rows.map(row=>'| '+row.join(' | ')+' |').join('\n')}`;
const htmlTable=(headers,rows)=>`<div class="scroll"><table><thead><tr>${headers.map(label=>`<th>${esc(label)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>'<tr>'+row.map(value=>`<td>${esc(value)}</td>`).join('')+'</tr>').join('')}</tbody></table></div>`;
const compHeaders=['Mesure','Next.js','Rustyx','Avantage observé'];
const compRows=comparisons.map(([label,n,r,unit,lower])=>[label,fmt(n,unit==='req/s'?0:unit==='ms'?3:2)+' '+unit,fmt(r,unit==='req/s'?0:unit==='ms'?3:2)+' '+unit,winner(n,r,lower)]);
const loadHeaders=['Charge','Moteur','Valides','RAM Mio','Pic Mio','CPU ms/rép.','CPU % cœur','Req/s','p95 ms','p99 ms','Corps Kio','CPU client %','Erreurs'];
const loadRows=runtime.flatMap(row=>engines.map(engine=>{
  const x=row[engine];return[`${row.label} · C${row.concurrency}`,names[engine],`${x.validRuns}/${x.runs}`,fmt(x.loadMedianRssMiB.median),fmt(x.sampledPeakRssMiB.max),fmt(x.cpuMsPerRequest.median,4),fmt(x.cpuPercentOneCore.median,1),fmt(x.requestsPerSecond.median,0),fmt(x.p95Ms.median),fmt(x.p99Ms.median),fmt(x.meanBodyBytes.median/1024),fmt(x.clientCpuPercent,1),x.errors];
}));
const buildHeaders=['État des caches','Moteur','Commande framework (s)','Contrôles ajoutés (s)','Total avec RSS (s)','CPU total (s)','Pic RSS médian (Mio)'];
const buildRows=['cold','warm'].flatMap(kind=>engines.map(engine=>{const b=build[kind][engine];return[kind==='cold'?'Vides':'Conservés',names[engine],fmt(b.frameworkMs.median/1000),engine==='next'?'Inclus':fmt(b.validationMs.median/1000),fmt(b.pipelineMs.median/1000),fmt(b.cpuMs.median/1000),fmt(b.sampledPeakTreeRssMiB.median)];}));
const browserHeaders=['Page','Moteur','TTFB ms','DOMContentLoaded ms','LCP local ms','JS reçu Kio','JS décodé Kio','Thread principal ms','Heap JS Mio'];
const browserRows=Object.entries(browser).flatMap(([route,values])=>engines.map(engine=>{const x=values[engine];return[route,names[engine],fmt(x.ttfbMs.median),fmt(x.domContentLoadedMs.median),fmt(x.lcpMs.median),fmt(x.jsEncodedBytes.median/1024),fmt(x.jsDecodedBytes.median/1024),fmt(x.mainThreadMs.median),fmt(x.jsHeapUsedMiB.median)];}));
const method=[
  'Même blog et mêmes dépendances corrigées, sources applicatives identiques (SHA-256 vérifié). Trois builds à froid et trois rebuilds sans modification par moteur ; trois répétitions de quatre secondes par charge de débit, et huit secondes à cadence imposée. Ordre des moteurs alterné pour les builds et les charges HTTP. Mesures médianes, sauf pics du tableau de charge : maximum observé.',
  'Build à froid : sorties .next/.rustyx, cache local du framework, Contentlayer et caches des contrôles supprimés. Cache disque du système conservé ; installation npm et compilation du binaire Rust exclues. Build complet : compilation, pré-rendu, contrôles et génération du flux RSS.',
  'Next 15.5 utilise ici webpack et réalise ses vérifications internes. Le build Rustyx brut n’effectue pas de lint ni de contrôle TypeScript. Pour la colonne « complet », ces deux vérifications sont ajoutées en parallèle, puis le même script RSS est exécuté. Le contrôle TypeScript commun désactive composite comme Next le fait dans runTypeCheck ; ce n’est pas une reproduction de tous les contrôles internes des routes Next.',
  'Production : un seul serveur testé à la fois, processus neuf par charge, configuration de workers par défaut, 140 requêtes d’échauffement. HTTP local, keep-alive, gzip accepté ; images WebP déjà mises en cache. Corps et statuts contrôlés. La charge newsletter n’est pas mesurée : aucun fournisseur externe n’est configuré.',
  'Comparaison à travail égal : 250 arrivées par seconde pendant huit secondes, soit 2 000 réponses par essai sur les mêmes sept pages. Au maximum 64 requêtes en vol. Le retard d’émission p95 reste inférieur à 1,1 ms pour chaque essai ; cette mesure sert de référence RAM/CPU et latence, indépendamment du débit maximal.',
  'Ce blog sert essentiellement des pages pré-rendues. Rustyx les distribue depuis son serveur natif : aucun worker Node n’est lancé pendant les charges mesurées. Ces chiffres ne représentent pas le coût d’un site avec SSR dynamique, authentification ou requêtes externes. Les serveurs de développement déjà ouverts sont restés inactifs pendant les mesures.',
  'RAM = somme du RSS du serveur et de ses descendants, échantillonnée environ toutes les 150 ms. Des pages partagées peuvent être comptées plusieurs fois. Le navigateur, le générateur de charge et le compilateur sont exclus de la RAM serveur. CPU serveur = variation du temps CPU cumulé via ps ; 100 % représente un cœur. Pour le build, time -l compte le CPU utilisateur + système.',
  'Le générateur partage la machine avec le serveur. Un CPU client proche de 100 % peut limiter le débit mesuré : les résultats de forte concurrence ne prouvent pas le plafond réel du serveur. Les corps HTML/Flight ont des tailles différentes et leur coût de transfert fait partie du résultat.',
  'Navigateur : Chromium, trois contextes neufs par page et moteur, cache désactivé, fenêtre 1280 × 900, sans limitation réseau/CPU. Ce sous-test est groupé : Next puis Rustyx. Chargements et préchargements par défaut inclus. Les temps LCP locaux ne constituent pas des Core Web Vitals mesurés chez les visiteurs. Le heap JavaScript n’est pas la RAM totale de Chromium.',
  'Taille de build : fichiers générés hors cache, avec les précompressions produites par chaque moteur ; node_modules et public exclus. Ce n’est pas la taille totale d’un déploiement autonome. Mesures sur un seul MacBook Air M4 ; les résultats peuvent différer sur un VPS Linux.',
  'Les essais pilotes ont révélé deux erreurs du protocole : un titre d’article attendu incorrect et une URL d’image sans le slash final exigé par la configuration Next. Les charges concernées ont été reprises pour les deux moteurs après correction. Les 21 échauffements rejetés sont archivés dans pilot-results.json ; ils ne sont pas des pannes applicatives et sont exclus des chiffres finaux.',
];
const functionality=data.contentComparisons.map(row=>[row.path,row.titleEqual?'Oui':'Écart',row.headingsEqual?'Oui':'Écart',row.mainTextEqual?'Oui':'Écart']);
const totalRequests=data.runs.reduce((sum,row)=>sum+(row.requests||0),0),errors=data.runs.reduce((sum,row)=>sum+(row.errors||0),0);
const findings=[
  `Build complet à froid : ${winner(comparisons[0][1],comparisons[0][2])}. Rebuild avec cache : ${winner(comparisons[1][1],comparisons[1][2])}.`,
  `À 250 requêtes/s sur les mêmes sept pages, la variation de RAM de Rustyx par rapport à Next est ${percent(-gain(fixed.next.loadMedianRssMiB.median,fixed.rustyx.loadMedianRssMiB.median))}, celle du CPU par réponse ${percent(-gain(fixed.next.cpuMsPerRequest.median,fixed.rustyx.cpuMsPerRequest.median))}. La latence p95 baisse de ${fmt(gain(fixed.next.p95Ms.median,fixed.rustyx.p95Ms.median),1)} %.`,
  'Sur ce blog statique, Rustyx est nettement plus économe en production. Next construit plus vite, utilise moins de CPU au build et conserve un avantage de débit sur le fichier JSON de recherche. Les temps côté navigateur sont partagés : Rustyx transfère moins de JavaScript, Next atteint DOMContentLoaded plus tôt.',
  `Point à améliorer chez Rustyx : le corps HTML gzip moyen des sept pages pèse ${fmt(fixed.rustyx.meanBodyBytes.median/1024)} Kio, contre ${fmt(fixed.next.meanBodyBytes.median/1024)} Kio pour Next (${percent(100*(fixed.rustyx.meanBodyBytes.median/fixed.next.meanBodyBytes.median-1))}). Le gain serveur ne garantit pas un chargement plus rapide sur une connexion lente.`,
  `${fmt(totalRequests,0)} réponses valides mesurées ; ${errors} erreur(s) de réponse ; ${data.invalidRuns||0} essai(s) invalide(s).`,
];
const md=`# Next.js / Rustyx sur le blog réel\n\n${data.finishedAt} · Next ${data.versions.next} · Rustyx ${data.versions.rustyx} · ${data.machine.cpu}, ${data.machine.ramGiB} Gio · Node ${data.versions.node}\n\n${findings.join('\n\n')}\n\n${markdownTable(compHeaders,compRows)}\n\n## Builds\n\n${markdownTable(buildHeaders,buildRows)}\n\n## Serveurs en production\n\n${markdownTable(loadHeaders,loadRows)}\n\n## Navigateur\n\n${markdownTable(browserHeaders,browserRows)}\n\n## Équivalence visible\n\n${markdownTable(['Page','Titre identique','En-têtes identiques','Texte principal identique'],functionality)}\n\n## Méthode et limites\n\n${method.map(text=>'- '+text).join('\n')}\n\n[Rapport interactif](index.html) · [Mesures brutes](results.json) · [Synthèse JSON](summary.json).\n`;
await writeFile(path.join(directory,'rapport.md'),md);
await writeFile(path.join(directory,'runtime.csv'),[loadHeaders,...loadRows].map(row=>row.map(value=>'"'+String(value).replaceAll('"','""')+'"').join(';')).join('\n')+'\n');
function bars(title,n,r,unit,lower=true){const max=Math.max(n,r,1);return`<article class="chart"><h3>${esc(title)}</h3><p class="muted">${lower?'Moins':'Plus'} est mieux · ${esc(unit)}</p>${[['next',n],['rustyx',r]].map(([engine,value])=>`<div class="bar-label"><span>${names[engine]}</span><b>${fmt(value,unit==='req/s'?0:2)}</b></div><div class="track"><div class="bar ${engine}" style="width:${value/max*100}%"></div></div>`).join('')}</article>`}
const html=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Le blog réel · Next.js / Rustyx</title><style>
:root{color-scheme:light;--ink:#142b37;--muted:#5c6f7b;--next:#3564d7;--rustyx:#158469}*{box-sizing:border-box}body{margin:0;background:#f2f5f7;color:var(--ink);font:15px/1.65 system-ui,sans-serif}main{max-width:1360px;margin:auto;padding:48px 28px}header{padding:38px 0 24px}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.17em;text-transform:uppercase;color:var(--rustyx)}h1{font-size:clamp(34px,5vw,64px);letter-spacing:-.055em;line-height:1.06;max-width:860px;margin:18px 0}h2{font-size:25px;letter-spacing:-.035em}h3{font-size:16px;margin:0}.lead{font-size:19px;max-width:920px;color:var(--muted)}.muted{color:var(--muted);font-size:13px}a{color:var(--next)}code{overflow-wrap:anywhere}.links{display:flex;gap:20px;flex-wrap:wrap}.panel,.chart{background:#fff;border:1px solid #dce5e9;border-radius:18px;padding:26px;margin:20px 0}.charts{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.chart{margin:0}.bar-label{display:flex;justify-content:space-between;margin-top:16px;font-size:13px}.track{height:13px;border-radius:7px;background:#edf1f5;overflow:hidden;margin-top:5px}.bar{height:100%;border-radius:7px}.next{background:var(--next)}.rustyx{background:var(--rustyx)}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap;font-variant-numeric:tabular-nums;font-size:13px}th,td{text-align:right;padding:12px 13px;border-bottom:1px solid #e7edf0}th{font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted)}th:first-child,td:first-child{text-align:left}tbody tr:hover{background:#f5f9fc}select{font:inherit;border:1px solid #bdced6;border-radius:9px;padding:10px;max-width:100%;background:white;color:var(--ink)}.screens{display:grid;grid-template-columns:1fr 1fr;gap:24px}.screens img{width:100%;max-height:640px;object-fit:cover;object-position:top;border:1px solid #dce5e9;border-radius:12px}.method p{max-width:1080px}.status{display:inline-block;background:#e3f5ee;color:#11684b;border-radius:50px;padding:7px 13px;font-size:13px;font-weight:650}footer{color:var(--muted);font-size:13px;margin:35px 0}@media(max-width:800px){main{padding:22px 16px}.charts,.screens{grid-template-columns:1fr}.panel{padding:18px}}
</style></head><body><main><header><div class="eyebrow">Mesures locales · application réelle · production</div><h1>Le même blog.<br>Deux moteurs, leurs résultats.</h1><p class="lead">Next.js ${esc(data.versions.next)} face à Rustyx ${esc(data.versions.rustyx)}, sur <strong>tailwind-nextjs-starter-blog</strong>. Compilation, consommation serveur et coût côté navigateur sont mesurés séparément.</p><p class="muted">${esc(data.machine.cpu)} · ${data.machine.ramGiB} Gio · ${esc(data.machine.os)}/${esc(data.machine.arch)} · ${esc(data.finishedAt)}</p><p class="status">${fmt(totalRequests,0)} réponses valides · ${errors} erreur(s) · ${data.invalidRuns||0} essai(s) invalide(s)</p><nav class="links"><a href="rapport.md">Rapport texte</a><a href="runtime.csv">Tableau CSV</a><a href="results.json">Données brutes</a><a href="summary.json">Synthèse JSON</a></nav></header>
<section class="panel"><h2>Ce que les chiffres permettent de conclure</h2>${findings.map(text=>`<p>${esc(text)}</p>`).join('')}<p>Il n’y a pas de score global arbitraire : le meilleur choix dépend du coût de build, de la RAM disponible, du CPU par réponse et des ressources envoyées au visiteur. « Proches » signifie un écart inférieur à 3 %, sans prétendre à un test statistique de significativité.</p>${htmlTable(compHeaders,compRows)}</section>
<section><h2>Comparer une charge de production</h2><p><label for="scenario">Charge : </label><select id="scenario">${runtime.map(row=>`<option value="${row.id}">${esc(row.label)} · C${row.concurrency}</option>`).join('')}</select></p><div class="charts" id="runtime-charts"></div><p class="muted" id="client-note"></p></section>
<section class="panel"><h2>Le coût du build</h2><p>Les colonnes « framework » ne couvrent pas les mêmes contrôles : Next les intègre, Rustyx les exécute séparément pour la mesure complète. RSS désigne ici le <em>flux de syndication du blog</em> dans le total ; les pics mémoire sont indiqués en Mio.</p>${htmlTable(buildHeaders,buildRows)}<p class="muted">Le cache chaud conserve les sorties et reconstruit des sources inchangées. Il ne mesure pas le temps de compilation après une modification de code.</p></section>
<div class="charts">${bars('Build complet à froid',comparisons[0][1],comparisons[0][2],'s')}${bars('Rebuild avec caches',comparisons[1][1],comparisons[1][2],'s')}${bars('Pic mémoire du build à froid',comparisons[3][1],comparisons[3][2],'Mio')}</div>
<section class="panel"><h2>CPU, RAM et latence sous charge</h2>${htmlTable(loadHeaders,loadRows)}<p class="muted">CPU ms/rép. : millisecondes CPU serveur par réponse réussie. CPU % cœur : utilisation d’un cœur. Corps : octets reçus après compression HTTP. Le pic correspond au maximum échantillonné parmi les répétitions.</p></section>
<section class="panel"><h2>Ce que reçoit le navigateur</h2>${htmlTable(browserHeaders,browserRows)}<p>Ces mesures complètent les temps du serveur : une réponse rapide peut contenir davantage de JavaScript à télécharger et exécuter. Le navigateur dispose ici du réseau local et de la puissance du Mac M4.</p></section>
<section class="panel"><h2>Les pages rendent-elles le même contenu ?</h2>${htmlTable(['Page','Titre identique','En-têtes identiques','Texte principal identique'],functionality)}<p>Thème et navigation sans rechargement vérifiés pour chaque moteur. Ces contrôles ciblés ne prouvent pas une compatibilité exhaustive.</p><div class="screens"><figure><figcaption>Next.js</figcaption><a href="next-home.png"><img src="next-home.png" alt="Accueil du blog compilé par Next.js" loading="lazy"></a></figure><figure><figcaption>Rustyx</figcaption><a href="rustyx-home.png"><img src="rustyx-home.png" alt="Accueil du blog compilé par Rustyx" loading="lazy"></a></figure></div></section>
<section class="panel method"><h2>Protocole, portée et limites</h2>${method.map(text=>`<p>${esc(text)}</p>`).join('')}<p>Sources applicatives comparées : <code>${esc(data.sourceHashes[0].sha256)}</code>. Binaire Rustyx : <code>${esc(data.binarySha256)}</code>.</p><p>Reproduction : <code>BLOG_BENCH_OUTPUT=reports/blog-comparison node scripts/bench-blog.mjs</code>, avec les copies préparées dans <code>projects/next</code> et <code>projects/rustyx</code>. Les journaux de chaque build et serveur se trouvent dans ce dossier.</p></section><footer>Résultats observés sur ce projet et ces versions. Aucun gain universel ni projection de capacité VPS n’est déduit de ce test local.</footer></main>
<script type="application/json" id="runtime-data">${JSON.stringify(runtime).replaceAll('<','\u003c')}</script><script>
const rows=JSON.parse(document.getElementById('runtime-data').textContent),select=document.getElementById('scenario');
function render(){const row=rows.find(row=>row.id===select.value),container=document.getElementById('runtime-charts');container.replaceChildren();for(const [key,title,unit,lower] of [['loadMedianRssMiB','Mémoire serveur','Mio',true],['cpuMsPerRequest','CPU par réponse','ms',true],row.ratePerSecond?['p95Ms','Latence p95 à 250 req/s','ms',true]:['requestsPerSecond','Débit observé','req/s',false]]){const card=document.createElement('article');card.className='chart';const heading=document.createElement('h3');heading.textContent=title;card.append(heading);const note=document.createElement('p');note.className='muted';note.textContent=(lower?'Moins':'Plus')+' est mieux · '+unit;card.append(note);const max=Math.max(row.next[key].median||0,row.rustyx[key].median||0,0.0001);for(const engine of ['next','rustyx']){const value=row[engine][key].median;const label=document.createElement('div');label.className='bar-label';const name=document.createElement('span');name.textContent=engine==='next'?'Next.js':'Rustyx';const number=document.createElement('b');number.textContent=value===null?'—':value.toLocaleString('fr-FR',{maximumFractionDigits:key==='requestsPerSecond'?0:key==='cpuMsPerRequest'?4:2});label.append(name,number);const track=document.createElement('div'),bar=document.createElement('div');track.className='track';bar.className='bar '+engine;bar.style.width=(value||0)/max*100+'%';track.append(bar);card.append(label,track)}container.append(card)}document.getElementById('client-note').textContent='CPU du générateur : Next '+Math.round(row.next.clientCpuPercent)+' % · Rustyx '+Math.round(row.rustyx.clientCpuPercent)+' %. '+(row.ratePerSecond?'Cadence imposée identique : '+row.ratePerSecond+' requêtes/s. Retard d’émission p95 : Next '+row.next.scheduleLagP95Ms.median.toFixed(2)+' ms, Rustyx '+row.rustyx.scheduleLagP95Ms.median.toFixed(2)+' ms.':'Proche de 100 %, le client peut limiter le débit.');}select.addEventListener('change',render);render();
</script></body></html>`;
await writeFile(path.join(directory,'index.html'),html);
console.log(markdownTable(compHeaders,compRows));
console.log(path.join(directory,'index.html'));
